MicroserviceswithAzure_Code/Chapter08/CircuitBreaker/CompositeWeb/Models/Counter.cs
namespace CompositeWeb.Models
{
    using System;

    public class Counter
    {
        public DateTime UpdatedAt { get; set; }

        public int Value { get; set; }
    }
}

MicroserviceswithAzure_Code/Chapter08/CircuitBreaker/CompositeWeb/Models/WeatherReport.cs
namespace CompositeWeb.Models
{
    using System;

    public class WeatherReport
    {
        public string Temprature { get; set; }

        public DateTime UpdatedAt { get; set; }

        public string Weather { get; set; }
    }
}

MicroserviceswithAzure_Code/Chapter08/CircuitBreaker/CompositeWeb/Controllers/HomeController.cs
namespace CompositeWeb.Controllers
{
    using System.Collections.Generic;
    using System.Linq;

    using Contracts;

    using Microsoft.AspNetCore.Http;
    using Microsoft.AspNetCore.Mvc;

    using Newtonsoft.Json;

    public class HomeController : Controller
    {
        private static readonly string RequestLog = nameof(RequestLog);
        public IActionResult Error()
        {
            return this.View();
        }

        public IActionResult Index()
        {
            List<RequestLog> requestLog = null;
            if (this.HttpContext.Session.Keys.Contains(RequestLog))
            {
                var value = this.HttpContext.Session.GetString(RequestLog);
                if (!string.IsNullOrWhiteSpace(value))
                {
                    requestLog = JsonConvert.DeserializeObject<List<RequestLog>>(value);
                }
            }
            if (requestLog == null)
            {
                requestLog = new List<RequestLog>();
            }

            return this.View(requestLog);
        }
    }
}

MicroserviceswithAzure_Code/Chapter08/CircuitBreaker/CompositeWeb/Controllers/WeatherViewComponent.cs
namespace CompositeWeb.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Diagnostics;
    using System.Fabric;
    using System.Linq;
    using System.Threading.Tasks;

    using Contracts;

    using Microsoft.AspNetCore.Http;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.ServiceFabric.Services.Client;
    using Microsoft.ServiceFabric.Services.Remoting.Client;

    using Newtonsoft.Json;

    public class WeatherViewComponent : ViewComponent
    {
        private static readonly string RequestLog = nameof(RequestLog);
        private static readonly Uri WeatherServiceUri =
            new Uri(FabricRuntime.GetActivationContext().ApplicationName + "/WeatherService");

        private readonly IWeatherService weatherServiceClient =
            ServiceProxy.Create<IWeatherService>(WeatherServiceUri, new ServicePartitionKey("basic"));

        public async Task<IViewComponentResult> InvokeAsync()
        {
            try
            {
                List<RequestLog> requestLog = null;
                if (this.HttpContext.Session.Keys.Contains(RequestLog))
                {
                    var value = this.HttpContext.Session.GetString(RequestLog);
                    if (!string.IsNullOrWhiteSpace(value))
                    {
                        requestLog = JsonConvert.DeserializeObject<List<RequestLog>>(value);
                    }
                }

                var watch = Stopwatch.StartNew();
                var result = await this.weatherServiceClient.GetReport("2010");
                watch.Stop();
                result.ResponseTimeInSeconds = watch.Elapsed.TotalSeconds;
                if (requestLog == null)
                {
                    requestLog = new List<RequestLog>();
                }

                requestLog.Add(new RequestLog { CircuitState = result.CircuitState, RequestDuration = result.ResponseTimeInSeconds, RequestTime = DateTime.UtcNow });
                this.HttpContext.Session.SetString(RequestLog, JsonConvert.SerializeObject(requestLog));
                return this.View(result);
            }
            catch (Exception e)
            {
                Console.WriteLine(e);
                throw;
            }
          
        }
    }
}

MicroserviceswithAzure_Code/Chapter08/CircuitBreaker/CompositeWeb/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"].</h2>
<h3>@ViewData["Message"]</h3>

<p>Use this area to provide additional information.</p>

MicroserviceswithAzure_Code/Chapter08/CircuitBreaker/CompositeWeb/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"].</h2>
<h3>@ViewData["Message"]</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

MicroserviceswithAzure_Code/Chapter08/CircuitBreaker/CompositeWeb/Views/Home/Index.cshtml
@using Microsoft.AspNetCore.Http
@model List<Contracts.RequestLog>
@{
    ViewData["Title"] = "Home Page";
}

<div class="row">
    <div class="col-md-4">
        <h2>Weather Widget</h2>
        <div id="weatherView" style="border: 1px solid black; padding: 10px; height: 300px;">
            @await Component.InvokeAsync("Weather")
        </div>
    </div>
    <div class="col-md-offset-4 col-md-4">
        <h2>Status</h2>
        <div id="alert-success" class="alert alert-info" style="padding: 5px;"><h4>The widget on this screen refreshes every 10 seconds.</h4></div>
        <br />
        <input id="cancelRefresh" class="btn btn-danger btn-block" type="button" value="Disable Auto Refresh" />
    </div>
</div>
<h2>Response Log</h2>
<table class="table table-bordered">
    <thead>
        <tr>
            <th>Request Time</th>
            <th>Circuit Status</th>
            <th>Request Duration(sec.)</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var log in Model)
        {
            var rowClass = "success";
            if (log.CircuitState.Equals("closed", StringComparison.OrdinalIgnoreCase))
            {
                rowClass = "danger";
            }
            <tr class="@rowClass">
                <td>@log.RequestTime.ToString("hh:mm:ss")</td>
                <td>@log.CircuitState</td>
                <td>@log.RequestDuration</td>
            </tr>
        }
    </tbody>
</table>
<script>
    $(document).ready(function () {
        var timeOut = setTimeout(function () {
            $('#alert-success').slideUp('slow').fadeOut(function () {
                window.location.reload();
            });
        }, 10000);

        $('#cancelRefresh').click(function () {
            clearTimeout(timeOut);
            return false;
        });
    });
</script>

MicroserviceswithAzure_Code/Chapter08/CircuitBreaker/CompositeWeb/Views/Shared/Components/Counter/Default.cshtml
@*@model CompositeWeb.Models.Counter
<h1>Counter: @Model.Value</h1>
<br />
<br />
<br />
<h4>Reported At: @Model.ReportTime.ToString("hh:mm:ss")</h4>
<h4>Circuit State: @Model.CircuitState</h4>
<h4>Request Duration: @Model.ResponseTimeInSeconds seconds</h4>*@

MicroserviceswithAzure_Code/Chapter08/CircuitBreaker/CompositeWeb/Views/Shared/Components/Weather/Default.cshtml
@model Contracts.WeatherReport
<h1>Temperature: @Model.Temperature &#176;C</h1>
<h1>Conditions: @Model.WeatherConditions</h1>
<br />
<h4>Reported At: @Model.ReportTime.ToString("hh:mm:ss")</h4>
<h4>Circuit State: @Model.CircuitState</h4>
<h4>Request Duration: @Model.ResponseTimeInSeconds seconds</h4>

MicroserviceswithAzure_Code/Chapter08/CircuitBreaker/CompositeWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    <environment names="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>
    @RenderSection("scripts", required: false)
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" />
    <environment names="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">CompositeWeb</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav"></ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
    </div>
</body>
</html>